
WAY_TYPES = {
    'AL': 'allée',
    'AR': 'ancienne route',
    'AT': 'autoroute',
    'AV': 'avenue',
    'BO': 'boulevard',
    'CA': 'carré ',
    'CE': 'cercle',
    'CH': 'chemin',
    'CI': 'circle',
    'CO': 'cours',
    'CR': 'croissant',
    'CS': 'concession',
    'CT': 'côte',
    'DE': 'desserte',
    'DO': 'domaine',
    'DR': 'drive',
    'DS': 'descente',
    'EC': 'échangeur',
    'EP': 'esplanade',
    'GA': 'garden',
    'IM': 'impasse',
    'JA': 'jardin',
    'KO': 'court',
    'KR': 'crescent',
    'LC': 'lac',
    'LN': 'lane',
    'MO': 'montée',
    'PL': 'place',
    'PR': 'promenade',
    'PS': 'passage',
    'PU': 'plateau',
    'RA': 'rang',
    'RD': 'road',
    'RG': 'ridge',
    'RL': 'ruelle',
    'RO': 'route',
    'RU': 'rue',
    'SN': 'sentier',
    'SQ': 'square',
    'ST': 'street',
    'TA': 'terrace',
    'TC': 'trait-carré ',
    'TE': 'terrasse',
    'TL': 'trail',
    'TV': 'traverse',
    'VO': 'voie'
}

WAY_LINKS = {
    "A": "à",
    "B":"à l'",
    "C":"à la",
    "D":"au",
    "E":"aux",
    "F":"chez",
    "G":"chez les",
    "H":"d'",
    "I":"d'en",
    "J":"de",
    "K":"de l'",
    "L":"de la",
    "M":"des",
    "N":"du",
    "O":"en",
    "P":"l'",
    "Q":"la",
    "R":"le",
    "S":"les",
    "T":"sur",
    "U":"sur l'",
    "V":"sur la",
    "W":"sur le",
    "X": "sur les"
}

CARDINAL_POINTS = {
    'E': 'Est',
    'N': 'Nord',
    'NE': 'Nord-Est',
    'NO': 'Nord-Ouest',
    'O': 'Ouest',
    'S': 'Sud',
    'SE': 'Sud-Est', 
    'SO': 'Sud-Ouest'
}